visibility: public
summary: BIOMAG Annotator plugin is a collection of assisted annotation tools for image labelling.
authors:
  - name: Reka Hollandi
    orcid: 0000-0002-4052-6846
  - name: David Bauer
    orcid: 0000-0003-4960-0368
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - Microscopy
  - Fluorescence microscopy
  - Confocal microscopy
  - Electron microscopy
  - Medical imaging
  - 2D image
  - Multi-channel image
  - Image annotation
  - Object detection
  - Image segmentation
  - Nucleus segmentation
  - Cell segmentation
  - Model-based segmentation
  - Object classification
  - Convolutional neural network
  - Supervised learning
